### ISSUE TITLE
Need to get a released packages

### ISSUE THREAD

**Issue by gwarf** [onedata/nagios-plugins-onedata#12]
Can you please finalize the travis deployment configuration and tag a new release so that the appropriate RPM is built and attached?
You can check https://docs.travis-ci.com/user/deployment/releases/ for the official documentation and check  https://github.com/EGI-Foundation/glite-info-update-endpoints/blob/master/.travis.yml#L40 for a working example.
We need a package to finally update the probe deployed at ARGO and fix the errors, cf https://ggus.eu/?mode=ticket_info&ticket_id=137218

**Comment by bkryza** [comment]
@gwarf Please check if this is ok: https://github.com/onedata/nagios-plugins-onedata/releases

**Comment by gwarf** [comment]
Perfect, thanks @bkryza !
