### ISSUE TITLE
Enable release versioning - tag repository and packages coherently

### ISSUE THREAD

**Issue by gwarf** [onedata/nagios-plugins-onedata#3]
The probe should be released and the repository should be tagged appropriately so that we can link a specific probe package to a specific source code version.

**Comment by gwarf** [comment]
It would be great also to have packages attached to each release.

**Comment by luman75** [comment]
@gwarf 
>It would be great also to have packages attached to each release.

what do you mean by packages attached?

**Comment by gwarf** [comment]
Creating a release in GitHub, then uploading/adding/attaching the packages to the release, so that they can be picked up and deployed by the monitoring team.
Like this basically: https://github.com/EGI-Foundation/glite-info-update-endpoints/releases/tag/2.0.14

**Comment by gwarf** [comment]
The RPM SPEC should also be updated with the appropriate version number.

**Comment by brucellino** [comment]
> Creating a release in GitHub, then uploading/adding/attaching the packages to the release, so that they can be picked up and deployed by the monitoring team.
@gwarf this can be done with a `release` deployment in Travis.
See https://docs.travis-ci.com/user/deployment/releases/
