### ISSUE TITLE
Why is bash a prerequisite if the shell used is sh?

### ISSUE THREAD

**Issue by brucellino** [onedata/nagios-plugins-onedata#6]
The probes are using `/bin/sh` as their shell, but the readme states that: 

> These Nagios probes have the following requirements in order to work properly:
> - bash

I can't see bash in the spec, so it seems it's _not_ needed. However, the probes use features outside of POSIX sh, _e.g._ 

` if [  "x${ONEDATA_HOST}" == "x" ] && [ "x${ONEDATA_NAGIOS_ENDPOINT}" == "x" ]; then`
which fails [SC2039](https://github.com/koalaman/shellcheck/wiki/Sc2039)

I propose adding bash to the spec and changing the shebang.

**Comment by bkryza** [comment]
@brucellino Done.

**Comment by brucellino** [comment]
Closed in  9ff8aa1
