### ISSUE TITLE
Please enable the repo in Travis

### ISSUE THREAD

**Issue by brucellino** [onedata/nagios-plugins-onedata#7]
Now that there's a Travisfile, can you please enable the repo on Travis and maybe add the badge to the README? I don't have rights.

**Comment by bkryza** [comment]
Done - but do you have any idea why after I merged your PR there is `.travis.yml` in the master branch?

**Comment by bkryza** [comment]
Ok nevermind - I know what's happening - I'll fix it...

**Comment by brucellino** [comment]
my apologies @bkryza it hadn't been added. See #9

**Comment by bkryza** [comment]
@brucellino build is running now: https://travis-ci.org/onedata/nagios-plugins-onedata/builds/432479755

**Comment by brucellino** [comment]
Awesome. Do you want to add the badge to the README or should I?

**Comment by bkryza** [comment]
I've already added it - but the build fails: https://github.com/onedata/nagios-plugins-onedata

**Comment by brucellino** [comment]
great! failing builds are a great sign :slightly_smiling_face: this seems to be a problem with the docker version on travis, i'll include a fix in #9 

At least now we can know whether my contributions makes sense, waiting for Travis to test them :+1:
